import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { execSync } from 'child_process';

export interface SkillFile {
  uri: vscode.Uri;
  relativePath: string;
  content: string;
}

export interface ActivityEntry {
  timestamp: string;  // ISO8601
  user: string;
  role: string;
  tool: string;
  workflow: string;
  summary: string;
}

// Ordered by priority — first match wins
const SKILL_FILENAMES = ['SKILL.md', 'skill.md', 'Skill.md', 'SKILL.MD'];

export class TeamContext {
  private workspaceRoot: vscode.Uri;
  private subdir: string;
  // undefined = not yet loaded; null = loaded and not found
  private skillCache: SkillFile | null | undefined = undefined;

  constructor(workspaceRoot: vscode.Uri, subdir: string) {
    this.workspaceRoot = workspaceRoot;
    this.subdir = subdir;
  }

  private get kernalDir(): vscode.Uri {
    return vscode.Uri.joinPath(this.workspaceRoot, this.subdir);
  }

  // Probe the workspace root for well-known manifest files to infer the stack.
  private async detectProjectType(): Promise<'typescript' | 'javascript' | 'python' | 'go' | 'rust' | 'java' | 'generic'> {
    const root = this.workspaceRoot.fsPath;
    const probe = (file: string): boolean => {
      try { fs.accessSync(path.join(root, file)); return true; } catch { return false; }
    };
    if (probe('tsconfig.json')) return 'typescript';
    if (probe('package.json')) {
      try {
        const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')) as Record<string, unknown>;
        const deps = { ...(pkg.dependencies as object | undefined), ...(pkg.devDependencies as object | undefined) };
        if ('typescript' in deps) return 'typescript';
      } catch { /* fall through */ }
      return 'javascript';
    }
    if (probe('pyproject.toml') || probe('setup.py') || probe('requirements.txt')) return 'python';
    if (probe('go.mod')) return 'go';
    if (probe('Cargo.toml')) return 'rust';
    if (probe('pom.xml') || probe('build.gradle') || probe('build.gradle.kts')) return 'java';
    return 'generic';
  }

  private generateConventions(type: 'typescript' | 'javascript' | 'python' | 'go' | 'rust' | 'java' | 'generic'): string {
    const stacks: Record<typeof type, string> = {
      typescript: `# Conventions
> Auto-generated by Kernal on first init. Edit to match your project.

## Language & runtime
- TypeScript strict mode (\`"strict": true\` in tsconfig). No \`any\` without a comment explaining why.
- Target: keep \`tsconfig.json\` \`target\` and \`lib\` in sync with the minimum Node.js version the project supports.
- \`esModuleInterop: true\`, \`skipLibCheck: true\`.

## Formatter & linter
- Prettier for formatting (config in \`.prettierrc\` or \`package.json\`). Run before every commit.
- ESLint with \`@typescript-eslint\`. Fix all errors; warnings are allowed only with a ticket attached.
- Import order: built-ins → third-party → internal (enforced by \`eslint-plugin-import\` or similar).

## Naming
- Files: \`camelCase.ts\` for modules, \`PascalCase.ts\` for classes/React components.
- Types and interfaces: \`PascalCase\`. Prefix interfaces with \`I\` only if the project already does so.
- Constants: \`UPPER_SNAKE_CASE\`. Private class fields: \`camelCase\` (no leading underscore).
- Boolean variables: prefix with \`is\`, \`has\`, \`can\`, \`should\`.

## Code style
- Prefer \`const\` over \`let\`; never \`var\`.
- Arrow functions for callbacks; \`function\` declarations for top-level named functions.
- Async/await over raw Promises. Avoid floating Promises — always \`void\` or \`await\` them.
- No barrel re-exports (\`index.ts\` that just re-exports everything) unless the package surface is intentional.
- Keep functions under ~40 lines. Extract when a function needs a comment to explain what a block does.

## PR rules
- Every PR needs: description of what changed and why, link to ticket/issue, screenshots for UI changes.
- No PR merges with TypeScript errors or ESLint errors.
- Test coverage must not decrease. New code needs tests (unit or integration, depending on what makes sense).
- Max ~400 lines changed per PR (excluding generated/lock files). Split larger changes.
- Squash merge preferred; keep commit messages in imperative mood.

## Testing
- Unit tests: Jest (or Vitest). Files: \`*.test.ts\` co-located with source.
- Integration tests: separate \`tests/\` directory.
- No mocking of the module under test. Mock only external I/O (network, disk, time).

## Things to avoid
- \`as any\` without a \`// eslint-disable\` + comment explaining the escape hatch.
- Synchronous file I/O (\`fs.readFileSync\`) on the hot path.
- \`console.log\` in committed code — use a structured logger.
- Importing from \`src/\` in test files using \`../../\` — use path aliases instead.
- Deeply nested callbacks or Promise chains — flatten with async/await.
`,
      javascript: `# Conventions
> Auto-generated by Kernal on first init. Edit to match your project.

## Language & runtime
- ES2020+ syntax. Use optional chaining (\`?.\`) and nullish coalescing (\`??\`) freely.
- CommonJS (\`require\`) or ESM (\`import\`) — pick one and stay consistent across the project.
- Node.js minimum version: set this in \`package.json\` \`engines\` field.

## Formatter & linter
- Prettier for formatting. Run before every commit.
- ESLint. Fix all errors; no ignored warnings without a ticket.
- Import order: built-ins → third-party → internal.

## Naming
- Files: \`camelCase.js\` for modules, \`PascalCase.js\` for classes.
- Constants: \`UPPER_SNAKE_CASE\`. Functions and variables: \`camelCase\`.
- Boolean variables: prefix with \`is\`, \`has\`, \`can\`, \`should\`.

## Code style
- \`const\` over \`let\`; never \`var\`.
- Async/await over raw callbacks or chained \`.then()\`.
- Keep functions focused — one responsibility, under ~40 lines.

## PR rules
- Every PR needs: description of change + reason, link to ticket, screenshots for UI changes.
- No PR merges with ESLint errors.
- Test coverage must not decrease.
- Max ~400 lines changed per PR (excluding lock files).

## Testing
- Jest (or Vitest). Test files: \`*.test.js\` or \`*.spec.js\`.
- Mock only I/O boundaries (HTTP, disk, time). Never mock the code under test.

## Things to avoid
- \`var\` declarations.
- Callback-style async (\`fs.readFile(path, cb)\`) — use \`fs.promises\` or \`util.promisify\`.
- \`console.log\` in committed code — use a structured logger.
- Deep relative imports (\`../../../utils\`) — use path aliases.
`,
      python: `# Conventions
> Auto-generated by Kernal on first init. Edit to match your project.

## Language & runtime
- Python 3.10+. Use \`match\` statements, structural pattern matching, and union types (\`X | Y\`) where appropriate.
- Virtual environment: \`venv\` or \`poetry\`. Never install packages globally.
- Dependencies: pinned in \`requirements.txt\` or \`pyproject.toml\`. Use \`pip-compile\` or Poetry lock file.

## Formatter & linter
- Black for formatting (line length 88). Run before every commit.
- Ruff for linting (replaces flake8 + isort + pyupgrade). All errors must be fixed.
- mypy or pyright for type checking in strict mode. New code must be fully typed.
- Pre-commit hooks: Black + Ruff + mypy.

## Naming
- Files and modules: \`snake_case.py\`.
- Classes: \`PascalCase\`. Functions, methods, variables: \`snake_case\`.
- Constants: \`UPPER_SNAKE_CASE\`.
- Private methods/attributes: prefix with \`_\`. Dunder methods only for operator overloading.
- Type aliases: \`PascalCase\` (e.g. \`UserId = NewType('UserId', int)\`).

## Code style
- Type-annotate every function signature (params + return type).
- Prefer dataclasses or Pydantic models over plain dicts for structured data.
- Context managers (\`with\`) for all resource management (files, DB connections, locks).
- List/dict/set comprehensions over \`map\`/\`filter\` for clarity. Generator expressions for large sequences.
- Keep functions under ~40 lines. Extract helpers rather than adding comments.

## PR rules
- Every PR needs: what changed and why, link to issue, test output snippet for logic changes.
- No merge with mypy errors or Ruff errors.
- Test coverage must not decrease. New logic needs unit tests.
- Max ~400 lines changed per PR (excluding generated files).

## Testing
- pytest. Test files: \`tests/test_*.py\`.
- Use \`pytest-mock\` for mocking. Mock only I/O (HTTP, DB, filesystem, time).
- Use \`pytest.mark.parametrize\` for table-driven tests.
- Fixtures in \`conftest.py\`, scoped appropriately (\`function\` default, \`session\` for expensive setup).

## Things to avoid
- Mutable default arguments (\`def f(x=[]):\`).
- Bare \`except:\` — always catch a specific exception type.
- \`print()\` in committed code — use the \`logging\` module.
- Importing \`*\` from any module.
- \`os.system()\` or \`subprocess\` with \`shell=True\` — use \`subprocess.run\` with a list of args.
`,
      go: `# Conventions
> Auto-generated by Kernal on first init. Edit to match your project.

## Language & runtime
- Go 1.21+. Use the version specified in \`go.mod\`.
- Modules: one module per repository unless the project is explicitly a multi-module monorepo.

## Formatter & linter
- \`gofmt\` / \`goimports\` on save (enforced in CI). Never commit unformatted code.
- \`golangci-lint\` with at minimum: \`errcheck\`, \`govet\`, \`staticcheck\`, \`gosec\`.
- \`go vet\` must pass on every PR.

## Naming
- Packages: short, lowercase, single word. No underscores.
- Exported types/functions: \`PascalCase\`. Unexported: \`camelCase\`.
- Interfaces: noun or noun-phrase (\`Reader\`, \`UserStore\`). Single-method interfaces: method name + \`er\`.
- Error variables: \`ErrFoo\` (exported) or \`errFoo\` (unexported).
- Test files: \`*_test.go\` in the same package.

## Code style
- Handle every error — never discard with \`_\` without a comment.
- Return errors as the last return value. Wrap with \`fmt.Errorf("context: %w", err)\` to preserve the chain.
- Prefer table-driven tests with \`t.Run\`.
- Use \`context.Context\` as the first argument of every function that does I/O.
- Keep interfaces small — define them where they are used, not where they are implemented.
- Goroutines must have a clear owner responsible for their lifecycle.

## PR rules
- Every PR needs: description, link to issue, \`go test ./...\` output for logic changes.
- No PR merges with \`go vet\` or \`golangci-lint\` errors.
- Test coverage must not decrease for business-logic packages.
- Max ~400 lines changed per PR (excluding generated files).

## Testing
- Standard \`testing\` package + \`testify/assert\` (if already in use).
- Integration tests: build tag \`//go:build integration\` and run separately in CI.
- No global state in tests — each test must be independent and parallel-safe (\`t.Parallel()\`).

## Things to avoid
- \`init()\` functions except in \`main\` packages.
- Global variables for anything other than sentinel errors and compile-time constants.
- \`interface{}\` / \`any\` except at true boundary points (JSON decode, plugin systems).
- Panics outside of \`main\` — return errors instead.
- \`time.Sleep\` in tests — use channels or \`sync.WaitGroup\`.
`,
      rust: `# Conventions
> Auto-generated by Kernal on first init. Edit to match your project.

## Language & toolchain
- Rust stable. MSRV is specified in \`Cargo.toml\` (\`rust-version\` field). Do not use nightly features.
- Edition: 2021.

## Formatter & linter
- \`rustfmt\` on save (enforced in CI via \`cargo fmt --check\`).
- \`clippy\` with \`-D warnings\` — all clippy warnings are errors. Run \`cargo clippy -- -D warnings\`.
- \`cargo audit\` in CI to catch vulnerable dependencies.

## Naming
- Types, traits, enums, enum variants: \`PascalCase\`.
- Functions, methods, variables, modules, crate names: \`snake_case\`.
- Constants and statics: \`UPPER_SNAKE_CASE\`.
- Lifetime parameters: short lowercase (\`'a\`, \`'db\`). Descriptive names for complex lifetimes.

## Code style
- Prefer \`Result\` and \`Option\` over panics. Reserve \`unwrap()\`/\`expect()\` for test code or truly impossible states (document why).
- Use \`thiserror\` for library errors, \`anyhow\` for application errors.
- Derive \`Debug\` on all public types. Derive \`Clone\`, \`PartialEq\` where it makes semantic sense.
- Prefer iterators over manual index loops. Avoid unnecessary allocations in hot paths.
- \`impl Trait\` in argument position for generic functions; explicit type parameters for return position when the type needs to be named by callers.

## PR rules
- Every PR needs: description, link to issue, \`cargo test\` output for logic changes.
- No PR merges with \`cargo clippy -- -D warnings\` failures or \`cargo fmt --check\` failures.
- Test coverage must not decrease for business-logic crates.
- Max ~400 lines changed per PR (excluding generated/\`Cargo.lock\`).

## Testing
- Unit tests: \`#[cfg(test)]\` module in the same file.
- Integration tests: \`tests/\` directory at the crate root.
- Use \`proptest\` or \`quickcheck\` for property-based tests on core data structures.
- No \`std::thread::sleep\` in tests — use channels or \`tokio::time::pause\` for async.

## Things to avoid
- \`unsafe\` blocks without a \`// SAFETY:\` comment explaining the invariants upheld.
- \`clone()\` on the hot path without benchmarks justifying it.
- Exposing \`pub\` items without doc comments.
- \`std::process::exit\` outside of \`main\`.
`,
      java: `# Conventions
> Auto-generated by Kernal on first init. Edit to match your project.

## Language & runtime
- Java 17+ (LTS). Use records, sealed classes, pattern matching, and text blocks where appropriate.
- Build tool: Maven or Gradle — be consistent, do not mix.
- JVM target: set \`sourceCompatibility\` / \`targetCompatibility\` in the build file.

## Formatter & linter
- Google Java Format or Checkstyle (config in repo). Run before every commit.
- SpotBugs or Error Prone in CI. All issues at severity HIGH+ must be fixed.
- PMD for code quality. Configure rules in \`pmd.xml\`.

## Naming
- Classes, interfaces, enums, annotations: \`PascalCase\`.
- Methods, variables, parameters: \`camelCase\`.
- Constants (\`static final\`): \`UPPER_SNAKE_CASE\`.
- Packages: all lowercase, reverse-domain (\`com.example.feature\`).
- Test classes: \`FooTest\` (unit) or \`FooIT\` (integration).

## Code style
- Prefer immutability: \`final\` fields, unmodifiable collections, records for DTOs.
- Use Optional for nullable return values from public APIs — never return \`null\` from a public method.
- Checked exceptions only for recoverable conditions. Use unchecked (RuntimeException) for programming errors.
- Constructor injection for dependencies (no field injection). Use a DI framework (\`Spring\`, \`Guice\`) consistently.
- Keep methods under ~30 lines. One level of abstraction per method.

## PR rules
- Every PR needs: description of change and rationale, ticket link, test evidence for logic changes.
- No merge with SpotBugs HIGH findings or Checkstyle violations.
- Test coverage must not decrease. New logic needs unit tests.
- Max ~400 lines changed per PR (excluding generated files).

## Testing
- JUnit 5. Test files: \`src/test/java/**/*Test.java\`.
- Mockito for mocking. Mock only external dependencies (HTTP, DB, file system).
- AssertJ for fluent assertions. Avoid raw JUnit \`assertEquals\`.
- Integration tests: \`@SpringBootTest\` or Testcontainers where full-stack testing is needed.

## Things to avoid
- Null returns from public methods — use Optional or throw.
- \`System.out.println\` in committed code — use SLF4J.
- Catching \`Exception\` or \`Throwable\` without re-throwing or specific handling.
- Mutable static state.
- String concatenation in loops — use StringBuilder.
`,
      generic: `# Conventions
> Auto-generated by Kernal on first init. Edit to match your project.

## Code style
- Be consistent with whatever style is already in the codebase. When in doubt, defer to the language's official style guide.
- Keep functions focused: one responsibility, short enough to read without scrolling.
- Prefer explicit over clever. Code is read far more often than it is written.

## Naming
- Names should describe intent, not implementation. A reader should not need to read the body to understand the name.
- Be consistent: if the codebase uses \`get_user\`, don't add \`fetchUser\`. Match existing conventions.
- Avoid abbreviations unless they are universally understood in this domain (\`id\`, \`url\`, \`db\` are fine; \`mgr\`, \`proc\`, \`tmp\` generally are not).

## PR rules
- Every PR needs: a description of what changed and why, a link to the relevant issue or ticket.
- No PR merges with broken tests or linter errors.
- Test coverage must not decrease on PRs that add business logic.
- Keep PRs focused — one concern per PR makes review faster and reverts cleaner.

## Testing
- Test at the boundary of your module, not its internals.
- Mock only I/O (network, filesystem, time). Do not mock the code under test.
- Each test must be independent and leave no shared state behind.

## Things to avoid
- Dead code — delete it, don't comment it out.
- Debug logging or print statements in committed code.
- Large, multi-purpose functions — split them.
- Inconsistent error handling — pick one strategy and apply it everywhere.
`,
    };
    return stacks[type];
  }

  async ensureScaffold(): Promise<void> {
    const dir = this.kernalDir;
    const projectType = await this.detectProjectType();
    const files: Record<string, string> = {
      'team.md': [
        '# Who we are',
        '',
        '<!-- Introduce your team here -->',
        '',
        '# Current sprint',
        '',
        '<!-- What are we building this sprint? -->',
        '',
        '# Key contacts',
        '',
        '<!-- Who to reach for what -->',
        '',
      ].join('\n'),

      'conventions.md': this.generateConventions(projectType),

      'prompts/review.md': [
        'Review the following code changes as if you are a senior teammate performing a pull-request review.',
        '',
        'For each issue found, classify it as one of:',
        '- **blocker** — must fix before merge',
        '- **suggestion** — strongly recommended improvement',
        '- **nit** — minor style or preference',
        '',
        'Focus on: correctness, adherence to project conventions, risk surface, and clarity.',
        'Skip obvious things that linters catch.',
        '',
      ].join('\n'),

      'prompts/standup.md': [
        'Write a brief, professional standup update in exactly three lines:',
        '',
        '**Yesterday:** What I completed.',
        '**Today:** What I will work on.',
        '**Blockers:** Any blockers, or "None".',
        '',
        'Base this on the git activity provided. Be concise — one sentence per line.',
        '',
      ].join('\n'),

      'prompts/explain.md': [
        'Explain the following code. Structure your answer as:',
        '',
        '1. **What it does** — one paragraph overview',
        '2. **Why it exists** — the purpose or problem it solves',
        '3. **Key invariants** — assumptions or constraints the code relies on',
        '4. **Where it\'s called from** — known callers or usage patterns',
        '',
        'Do not walk through it line by line.',
        '',
      ].join('\n'),

      'activity.jsonl': '',

      'README.md': [
        '# .kernal/',
        '',
        'This folder contains Kernal\'s team context files. **Commit it to git** so the whole team benefits.',
        '',
        '## Files',
        '',
        '- `team.md` — team intro, sprint, contacts',
        '- `conventions.md` — coding and PR conventions',
        '- `prompts/` — per-workflow prompt templates',
        '- `activity.jsonl` — append-only log of AI activity (newest entries at end)',
        '- `decisions/` — architectural decision records',
        '',
      ].join('\n'),
    };

    for (const [relPath, content] of Object.entries(files)) {
      const uri = vscode.Uri.joinPath(dir, relPath);
      try {
        await vscode.workspace.fs.stat(uri);
        // exists — never overwrite scaffold files
      } catch {
        const parentUri = vscode.Uri.joinPath(uri, '..');
        await vscode.workspace.fs.createDirectory(parentUri);
        await vscode.workspace.fs.writeFile(uri, Buffer.from(content, 'utf8'));
      }
    }

    const decisionsDir = vscode.Uri.joinPath(dir, 'decisions');
    try {
      await vscode.workspace.fs.stat(decisionsDir);
    } catch {
      await vscode.workspace.fs.createDirectory(decisionsDir);
    }
  }

  async hasRootSkill(): Promise<boolean> {
    const skill = await this.loadRootSkill();
    return skill !== null;
  }

  private async loadRootSkill(): Promise<SkillFile | null> {
    if (this.skillCache !== undefined) return this.skillCache;

    for (const name of SKILL_FILENAMES) {
      const uri = vscode.Uri.joinPath(this.workspaceRoot, name);
      try {
        const bytes = await vscode.workspace.fs.readFile(uri);
        const content = Buffer.from(bytes).toString('utf8');
        this.skillCache = { uri, relativePath: name, content };
        return this.skillCache;
      } catch {
        // not found, try next variant
      }
    }

    this.skillCache = null;
    return null;
  }

  async refreshSkillCache(): Promise<SkillFile | null> {
    this.skillCache = undefined;
    return this.loadRootSkill();
  }

  private async findNearestSkill(activeFile: vscode.Uri): Promise<SkillFile | null> {
    const rootFsPath = this.workspaceRoot.fsPath;

    // Resolve symlinks on both root and active file to prevent traversal escapes.
    let realRoot: string;
    let realActiveDir: string;
    try {
      realRoot = fs.realpathSync(rootFsPath);
      realActiveDir = path.dirname(fs.realpathSync(activeFile.fsPath));
    } catch {
      return null;
    }

    let dir = realActiveDir;
    while (dir === realRoot || dir.startsWith(realRoot + path.sep)) {
      for (const name of ['SKILL.md', 'skill.md']) {
        const candidate = path.join(dir, name);
        // Re-resolve the candidate to catch symlinks inside the tree.
        let realCandidate: string;
        try { realCandidate = fs.realpathSync(candidate); } catch { continue; }
        if (realCandidate !== realRoot && !realCandidate.startsWith(realRoot + path.sep)) {
          continue; // symlink escape — skip
        }
        const uri = vscode.Uri.file(candidate);
        try {
          const bytes = await vscode.workspace.fs.readFile(uri);
          const content = Buffer.from(bytes).toString('utf8');
          const relativePath = path.relative(rootFsPath, candidate);
          return { uri, relativePath, content };
        } catch {
          // not found at this level
        }
      }
      const parent = path.dirname(dir);
      if (parent === dir) break; // filesystem root
      dir = parent;
    }

    return null;
  }

  async loadContextBundle(activeFile?: vscode.Uri): Promise<string> {
    const parts: string[] = [];

    const rootSkill = await this.loadRootSkill();
    if (rootSkill) {
      parts.push(
        `# PROJECT SKILL (authoritative — overrides anything below if conflicting)\nSource: ${rootSkill.relativePath}\n\n${rootSkill.content}`
      );
    }

    if (activeFile) {
      const nested = await this.findNearestSkill(activeFile);
      if (nested && nested.uri.fsPath !== (rootSkill?.uri.fsPath ?? '')) {
        const dirname = path.dirname(nested.relativePath);
        parts.push(
          `# NESTED SKILL (more specific, applies to ${dirname})\nSource: ${nested.relativePath}\n\n${nested.content}`
        );
      }
    }

    const teamUri = vscode.Uri.joinPath(this.kernalDir, 'team.md');
    try {
      const bytes = await vscode.workspace.fs.readFile(teamUri);
      parts.push(`# team.md\n${Buffer.from(bytes).toString('utf8')}`);
    } catch { /* skip if missing */ }

    const conventionsUri = vscode.Uri.joinPath(this.kernalDir, 'conventions.md');
    try {
      const bytes = await vscode.workspace.fs.readFile(conventionsUri);
      parts.push(`# conventions.md\n${Buffer.from(bytes).toString('utf8')}`);
    } catch { /* skip if missing */ }

    const gitCtx = this.loadGitContext();
    if (gitCtx) parts.push(gitCtx);

    return parts.join('\n\n---\n\n');
  }

  private loadGitContext(): string {
    const cwd = this.workspaceRoot.fsPath;
    try {
      const branch = (execSync('git rev-parse --abbrev-ref HEAD', {
        cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
      }) as string).trim();
      const log = (execSync('git log --oneline -5', {
        cwd, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
      }) as string).trim();
      if (!branch && !log) return '';
      const lines = ['# Git Context'];
      if (branch) lines.push(`Branch: \`${branch}\``);
      if (log) lines.push('', 'Last 5 commits:', log);
      return lines.join('\n');
    } catch {
      return '';
    }
  }

  async readPrompt(name: string): Promise<string | undefined> {
    const uri = vscode.Uri.joinPath(this.kernalDir, 'prompts', name);
    try {
      const bytes = await vscode.workspace.fs.readFile(uri);
      return Buffer.from(bytes).toString('utf8');
    } catch {
      return undefined;
    }
  }

  private writeQueue: Promise<void> = Promise.resolve();

  async appendActivity(entry: ActivityEntry): Promise<void> {
    this.writeQueue = this.writeQueue.then(() => this.doAppendActivity(entry));
    await this.writeQueue;
  }

  private async doAppendActivity(entry: ActivityEntry): Promise<void> {
    const uri = vscode.Uri.joinPath(this.kernalDir, 'activity.jsonl');
    let lines: string[] = [];
    try {
      const bytes = await vscode.workspace.fs.readFile(uri);
      lines = Buffer.from(bytes).toString('utf8').split('\n').filter(l => l.trim());
    } catch { /* file may not exist yet */ }
    lines.push(JSON.stringify(entry));
    if (lines.length > 1000) lines = lines.slice(-1000);
    await vscode.workspace.fs.writeFile(uri, Buffer.from(lines.join('\n') + '\n', 'utf8'));
  }

  async readActivity(limit = 50): Promise<ActivityEntry[]> {
    const uri = vscode.Uri.joinPath(this.kernalDir, 'activity.jsonl');
    try {
      const bytes = await vscode.workspace.fs.readFile(uri);
      const lines = Buffer.from(bytes).toString('utf8').split('\n').filter(l => l.trim());
      const entries: ActivityEntry[] = [];
      for (const line of lines) {
        try {
          entries.push(JSON.parse(line) as ActivityEntry);
        } catch { /* ignore malformed lines */ }
      }
      return entries.slice(-limit).reverse();
    } catch {
      return [];
    }
  }
}
